- name: Deploy CI/CD application
  hosts: web
  become: true

  tasks:
    - name: Pull latest application image
      community.docker.docker_image:
        name: mahmoudtarek3500/cicd-node-app
        tag: latest
        source: pull
        force_source: true

    - name: Run application container
      community.docker.docker_container:
        name: cicd-container
        image: mahmoudtarek3500/cicd-node-app:latest
        state: started
        restart_policy: unless-stopped
        ports:
          - "3000:3000"
